name: 🚀 Deploy Dashboard to Server

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
    - name: List output directory 
      run: ls -R out
      
    - name: Deploy to cPanel
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 46.202.195.31
        username: defipulsex-app
        password: TLOVogDt3mUThvQYVo5B
        local_path: './out/*'
        remote_path: '/home/defipulsex-app/htdocs/www.app.defipulsex.com'
