name: 🚀 Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout Repository
      uses: actions/checkout@v4

    - name: 🛠 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 📦 Install Dependencies
      run: yarn install --frozen-lockfile

    - name: 🔨 Build Next.js App
      run: yarn build
      env:
        # Add any environment variables needed for the build
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    - name: 🔒 Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: 📂 Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the project directory
          cd /home/${{ secrets.SERVER_USER }}/public_html

          # Pull the latest code
          git pull origin main

          # Install production dependencies
          yarn install --production --frozen-lockfile

          # Build the Next.js app
          yarn build

          # Ensure PM2 is installed
          npm list -g pm2 || npm install -g pm2

          # Start or restart the Next.js app with PM2
          pm2 restart nextjs-app || pm2 start yarn --name "nextjs-app" -- start

          # Save the PM2 process list
          pm2 save
