name: 🚀 Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install and Build
        run: |
          yarn install
          yarn build

      - name: 🚀 Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            
            echo "Installing Node.js..."
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get update || { echo "apt-get update failed"; exit 1; }
            sudo apt-get install -y nodejs || { echo "apt-get install nodejs failed"; exit 1; }

            echo "Node.js version installed:"
            node -v

            echo "Yarn version installed:"
            yarn -v

            echo "Installing global dependencies..."
            yarn global add pm2 || { echo "Yarn global add pm2 failed"; exit 1; }

            echo "Deploying the application..."

            cd /home/${{ secrets.SERVER_USER }}/public_html

            git pull origin main || { echo "Git pull failed"; exit 1; }

            yarn install --frozen-lockfile || { echo "Dependency installation failed"; exit 1; }

            yarn build || { echo "Build process failed"; exit 1; }

            if pm2 describe nextjs-app > /dev/null; then
              pm2 reload nextjs-app || { echo "PM2 reload failed"; exit 1; }
            else
              pm2 start yarn --name "nextjs-app" -- run start || { echo "PM2 start failed"; exit 1; }
            fi

            pm2 save
