name: 🚀 Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install and Build
        run: |
          yarn install
          yarn build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e

            echo "Checking Node.js version..."
            node -v || echo "Node.js is not installed. Install it first."

            echo "Checking if Yarn is installed..."
            if ! command -v yarn > /dev/null; then
              echo "Installing Yarn..."
              curl -o- -L https://yarnpkg.com/install.sh | bash
              export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
            fi

            echo "Pulling latest code from Git..."
            cd /home/${{ secrets.SERVER_USER }}/public_html
            git reset --hard
            git pull origin main || { echo "Git pull failed"; exit 1; }

            echo "Installing dependencies with Yarn..."
            yarn install --frozen-lockfile || { echo "Yarn install failed"; exit 1; }

            echo "Building the application..."
            yarn build || { echo "Build failed"; exit 1; }

            echo "Starting or reloading the application with PM2..."
            npx pm2 describe nextjs-app > /dev/null && npx pm2 reload nextjs-app || npx pm2 start yarn --name "nextjs-app" -- run start

            echo "Saving PM2 process list..."
            npx pm2 save

            echo "Deployment successful!"
          EOF
