name: 🚀 Deploy Dashboard to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Step 3: Install dependencies
    # - name: Install dependencies
    #   run: npm ci

    # # Step 4: Build project
    # - name: Build project
    #   run: npm run build

    # Step 5: Deploy to cPanel
    - name: Deploy to cPanel
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 147.93.86.12
        username: gridape-app
        password: ${{ secrets.PASSWORD }}
        local_path: './*'
        remote_path: '/home/gridape-app/htdocs/www.app.gridape.com'
