name: 🚀 Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install and Build
        run: |
          yarn install
          yarn build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /home/${{ secrets.SERVER_USER }}/public_html &&
                                git pull origin main &&
                                yarn install --frozen-lockfile &&
                                yarn build &&
                                if pm2 describe nextjs-app > /dev/null; then
                                  pm2 reload nextjs-app;
                                else
                                  pm2 start yarn --name 'nextjs-app' -- run start;
                                fi &&
                                pm2 save"
