name: Deploy to Contabo VPS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H vmi2322505.contaboserver.net >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "SSH key and known hosts set up successfully."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@213.199.61.72 "echo 'SSH Connection Successful'"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 213.199.61.72
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            set -e
            echo "Starting deployment..."
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/public_html" ]; then
                echo "Project directory missing. Cloning repository..."
                mkdir -p /home/${{ secrets.SERVER_USER }}/public_html
                cd /home/${{ secrets.SERVER_USER }}/public_html
                git clone https://x-access-token:${{ secrets.SECRET_PAT }}@github.com/gridape/v1.git .
            else
                cd /home/${{ secrets.SERVER_USER }}/public_html
                echo "Project directory exists. Pulling latest changes..."
                if [ ! -d ".git" ]; then
                    echo "No .git repository found. Initializing repository..."
                    git init
                    git remote add origin https://x-access-token:${{ secrets.SECRET_PAT }}@github.com/gridape/v1.git
                fi
                git fetch origin main
                git reset --hard origin/main
            fi
            echo "Installing dependencies..."
            npm ci || { echo "Dependency installation failed."; df -h; exit 1; }
            echo "Building application..."
            npm run build || { echo "Build failed."; exit 1; }
            echo "Deployment completed successfully."

