
name: build and publish docker image
on: push

jobs:
   build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
  
      - name: Build and push Docker images

        uses: docker/build-push-action@v6.10.0
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build Image
        run: |
         docker build -t GridApe:v1.
            docker tag GridApe:v1 cliuzy1/GridApe:v1
            docker push cliuzy1/GridApe:v1
