
name: build and publish docker image
on: push

jobs:
   build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
  
      - name: Build and push Docker images

        uses: docker/build-push-action@v6.10.0
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build Image
        run: |
            docker build -t Silfrica-Backend:v1 .
            docker tag Silfrica-Backend:v1 cliuzy1/Silfrica-backend:v1
            docker push cliuzy1/Silfrica-backend:v1
